decade = 100
name = input("Hi! What's your name? ")
print("Hello " + name)
age = input("How old are you? ")
print("Cool! I didn't know you were " + age)
intage = int(age)
till100 = (decade-intage)
yearstillage = int(till100)
ending = str(yearstillage+2019)
print("That means you should turn 100 in " + ending)